SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
LINE_WIDTH = 2
STARTING_SCORE = 0

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 200
PLAYER_DECELERATION = 40
PLAYER_MAX_SPEED = 350
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
PLAYER_STARTING_LIVES = 3
PLAYER_INVULNERABILITY_SECONDS = 2

SHOT_LIFETIME_SECONDS = 3
SHOT_RADIUS = 5

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
MAX_ASTEROID_COUNT = 70

EXPLOSION_RADIUS = 1
EXPLOSION_TIMER = 0.75

MIN_STAR_COUNT = 50
MAX_STAR_COUNT = 200
STAR_SYMBOLS = (".", "*", "+", "x")
MIN_TWINKLE_INTERVAL = 0.3
MAX_TWINKLE_INTERVAL = 1.5

LAYER_WORLD = 10
LAYER_UFO = 12
LAYER_PICKUPS = 15
LAYER_PLAYER = 20
LAYER_PROJECTILES = 30
LAYER_EFFECTS = 40

PICKUP_RADIUS = 15
SPEED_BOOST_MULTIPLIER = 1.15
SPEED_BOOST_DURATION_SECONDS = 30.0
PICKUP_SPAWN_DELAY_SECONDS = 30.0
PICKUP_DROP_CHANCE = 0.10
PICKUP_LIFETIME_SECONDS = 90.0

UFO_RADIUS = 20
UFO_ACCELERATION = 400
UFO_DECELERATION = 200
UFO_MAX_SPEED = 360
UFO_SHOOT_SPEED = 500
UFO_SHOOT_COOLDOWN_SECONDS = 0.3
UFO_COLOR = (180, 180, 190)
UFO_MIN_DISTANCE = 200
UFO_MAX_DISTANCE = 250
UFO_MAX_COUNT = 10
UFO_SPAWN_CHANCE = 0.05
UFO_INITIAL_SPAWN_DELAY_SECONDS = 60.0
UFO_CAP_INCREASE_INTERVAL_SECONDS = 30.0
UFO_BULLET_RADIUS = 2
UFO_SCORE_VALUE = 10